### ISSUE TITLE
Cannot enter stream url

### ISSUE THREAD

**Issue by therobotguyllc** [pstuart/Generic-Video-Camera#1]
Love the work so far but when adding a camera with the connect smartapp there are two locations where I can enter a "stream path" however, the first is 3-option drop down menu where all 3 options are "name of camera" and the second entry box allows me to enter the url but the camera stream is never located.

I tried selecting "name of camera" in the first box and then typing my stream path in the name but that also did not work.

**Comment by pstuart** [comment]
So, the drop down list is where you can edit the smartapp child in the ide and add in your cameras so you can have a permanent list of cameras.  The input box is for adding cameras manually.  Don't select anything in the dropdown box if you want to enter a stream path in the input box.

**Comment by therobotguyllc** [comment]
I am afraid I do not know what the problem is then. I set the stream url which I know works but it can't retrieve it.

**Comment by pstuart** [comment]
Because you selected something in the drop down, ST has a bug that refuses to unselect this.  You will need to remove the smartapp child and re-add a camera, ignoring the dropdown and just entering a value for the url in the input box.
